### ISSUE TITLE
Figures have wrong title

### ISSUE THREAD

**Issue by davidak** [NAIST-SE/study-of-microsofts-github-acquisition#4]
https://naist-se.github.io/study-of-microsofts-github-acquisition/survey/result-3/

Figure Figure 3-2 has same title as Figure 3-1, but should have something about "additional efforts to change platforms from GitHub".

![screenshot from 2018-08-09 10-20-27](https://user-images.githubusercontent.com/91113/43887311-b06929fa-9bbe-11e8-8c65-2563273bd9f4.png)

Figure 4-4 also has the same title.

![screenshot from 2018-08-09 10-28-16](https://user-images.githubusercontent.com/91113/43887406-0b00e9ac-9bbf-11e8-83ef-0d6b474cba2f.png)

**Comment by hideakihata** [comment]
Thank you!

Correct titles are
- _If the project will be moved away from GitHub to another platform, how much additional effort will be required to get accustomed to the new platform?_ for **Figure 3-2**
- _How much additional effort will be required to get accustomed to the new platform?_ for **Figure 4-4**

We will fix them later.
